services:
  web:
    build: .
    ports:
      - "8099:80"
    environment:
      APP_ENV: dev
      SERVER_NAME: ":80"
    volumes:
      - .:/app
      - vendor_data:/app/vendor

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8030:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  vendor_data: